-- ARCH-MIG-01 slice 3 — assessment audit record (gap analysis §6, D8; SD-12).
--
-- Replaces triage_usage_log's prose fields (presentation_text / ai_response_summary
-- / ai_response_json) with a structured record: the QuestionnaireResponse the engine
-- evaluated (every value with its evidence status and quote), the Advisory it
-- produced, and the versions stamped on it (invariant 8). No note text lives here.
--
-- The redacted note, if a reviewer ever needs the prose, is a SEPARATE table with
-- its own retention class and a purge job — written only when AUDIT_STORE_REDACTED_NOTE
-- is on (default off). triage_usage_log is untouched; migrating its role is slice 10.

CREATE TABLE IF NOT EXISTS assessments (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the evaluate route
  created_at TEXT NOT NULL,            -- ISO timestamp
  bundle_versions TEXT NOT NULL,       -- JSON: { "national-redflags": "1.0.0", "<examSiteId>": "<version>", ... }
  engine_version TEXT NOT NULL,
  vocabulary_version TEXT,
  prompt_version TEXT,                 -- null for a no-model evaluate call; set by the slice 5 pipeline
  model_id TEXT,                       -- null for a no-model evaluate call
  documentation_standard TEXT NOT NULL,
  questionnaire_response TEXT NOT NULL,-- JSON: the QR the engine evaluated
  advisory TEXT NOT NULL,              -- JSON: the aggregated engine result (determination, redirects, missing, trace, alternatives)
  discrepancies TEXT,                  -- JSON: from the merge stage (slice 5); null here
  validation_failures TEXT,            -- JSON: from the validation gate (slice 4b); null here
  performed_by TEXT,
  regression_run_id TEXT               -- set for benchmark runs (slice 9)
);

CREATE INDEX IF NOT EXISTS idx_assessments_created ON assessments(created_at);
CREATE INDEX IF NOT EXISTS idx_assessments_regression ON assessments(regression_run_id);

-- Separate table, separate retention class. A row is written only when
-- AUDIT_STORE_REDACTED_NOTE is 'true' (default off). The Cron Trigger purge job
-- (worker.ts scheduled handler) deletes rows older than AUDIT_NOTE_RETENTION_DAYS
-- (default 180) — this table only.
CREATE TABLE IF NOT EXISTS assessment_notes (
  assessment_id TEXT PRIMARY KEY,      -- FK -> assessments.id
  note_redacted TEXT NOT NULL,         -- PII-redacted note text; residual (unverified redaction) risk — KI-34
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_assessment_notes_created ON assessment_notes(created_at);
